image: hseeberger/scala-sbt

before_script:
  - apt-get update -qq && apt-get install -y -qq tesseract-ocr imagemagick

stages:
  - test
  - package

test:
  stage: test
  script: "sbt -sbt-dir /cache/.sbt -ivy /cache/.ivy2 test"

package:
  stage: package
  script: "sbt assembly"
  artifacts:
    paths:
      - target/scala-2.11/poke-analyzer-assembly-*.jar